// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RestauranForManager.Data;
using System;

namespace RestauranForManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180422133626_MigrationDb")]
    partial class MigrationDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestauranForManager.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CheckAmount");

                    b.Property<DateTime>("ClosedDate");

                    b.Property<DateTime>("OpenedDate");

                    b.Property<int?>("StateId");

                    b.Property<double>("Tips");

                    b.Property<double>("TotalPrice");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestauranForManager.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Media");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RestauranForManager.Models.OrderItemsOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("OrderId");

                    b.Property<int?>("OrderItemsId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemsId");

                    b.ToTable("OrderItemsOrder");
                });

            modelBuilder.Entity("RestauranForManager.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("State");
                });

            modelBuilder.Entity("RestauranForManager.Models.Order", b =>
                {
                    b.HasOne("RestauranForManager.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("RestauranForManager.Models.OrderItemsOrder", b =>
                {
                    b.HasOne("RestauranForManager.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("RestauranForManager.Models.OrderItems", "OrderItems")
                        .WithMany("Orders")
                        .HasForeignKey("OrderItemsId");
                });
#pragma warning restore 612, 618
        }
    }
}
